/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AccountConfig extends PersistentObject {
    private transient long swigCPtr;

    protected AccountConfig(long cPtr, boolean cMemoryOwn) {
        super(pjsua2JNI.AccountConfig_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    protected static long getCPtr(AccountConfig obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_AccountConfig(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public void setIdUri(String value) {
        pjsua2JNI.AccountConfig_idUri_set(swigCPtr, this, value);
    }

    public String getIdUri() {
        return pjsua2JNI.AccountConfig_idUri_get(swigCPtr, this);
    }

    public AccountRegConfig getRegConfig() {
        long cPtr = pjsua2JNI.AccountConfig_regConfig_get(swigCPtr, this);
        return (cPtr == 0) ? null : new AccountRegConfig(cPtr, false);
    }

    public AccountSipConfig getSipConfig() {
        long cPtr = pjsua2JNI.AccountConfig_sipConfig_get(swigCPtr, this);
        return (cPtr == 0) ? null : new AccountSipConfig(cPtr, false);
    }

    public AccountNatConfig getNatConfig() {
        long cPtr = pjsua2JNI.AccountConfig_natConfig_get(swigCPtr, this);
        return (cPtr == 0) ? null : new AccountNatConfig(cPtr, false);
    }

    public AccountConfig() {
        this(pjsua2JNI.new_AccountConfig(), true);
    }
}
