/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AccountSipConfig extends PersistentObject {
    private transient long swigCPtr;

    protected AccountSipConfig(long cPtr, boolean cMemoryOwn) {
        super(pjsua2JNI.AccountSipConfig_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    protected static long getCPtr(AccountSipConfig obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_AccountSipConfig(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public AuthCredInfoVector getAuthCreds() {
        long cPtr = pjsua2JNI.AccountSipConfig_authCreds_get(swigCPtr, this);
        return (cPtr == 0) ? null : new AuthCredInfoVector(cPtr, false);
    }

    public StringVector getProxies() {
        long cPtr = pjsua2JNI.AccountSipConfig_proxies_get(swigCPtr, this);
        return (cPtr == 0) ? null : new StringVector(cPtr, false);
    }
}
