/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AccountNatConfig extends PersistentObject {
    private transient long swigCPtr;

    protected AccountNatConfig(long cPtr, boolean cMemoryOwn) {
        super(pjsua2JNI.AccountNatConfig_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    protected static long getCPtr(AccountNatConfig obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_AccountNatConfig(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public void setIceEnabled(boolean value) {
        pjsua2JNI.AccountNatConfig_iceEnabled_set(swigCPtr, this, value);
    }
}
