/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AudioMedia extends Media {
    private transient long swigCPtr;

    protected AudioMedia(long cPtr, boolean cMemoryOwn) {
        super(pjsua2JNI.AudioMedia_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    protected static long getCPtr(AudioMedia obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_AudioMedia(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public void startTransmit(AudioMedia sink) throws java.lang.Exception {
        pjsua2JNI.AudioMedia_startTransmit(swigCPtr, this, AudioMedia.getCPtr(sink), sink);
    }

    public static AudioMedia typecastFromMedia(Media media) {
        long cPtr = pjsua2JNI.AudioMedia_typecastFromMedia(Media.getCPtr(media), media);
        return (cPtr == 0) ? null : new AudioMedia(cPtr, false);
    }

}
