/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AuthCredInfo extends PersistentObject {
    private transient long swigCPtr;

    protected AuthCredInfo(long cPtr, boolean cMemoryOwn) {
        super(pjsua2JNI.AuthCredInfo_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    protected static long getCPtr(AuthCredInfo obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_AuthCredInfo(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public String getUsername() {
        return pjsua2JNI.AuthCredInfo_username_get(swigCPtr, this);
    }

    public String getData() {
        return pjsua2JNI.AuthCredInfo_data_get(swigCPtr, this);
    }

    public AuthCredInfo(String scheme, String realm, String user_name, int data_type, String data) {
        this(pjsua2JNI.new_AuthCredInfo__SWIG_1(scheme, realm, user_name, data_type, data), true);
    }
}
