/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class Call {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Call(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(Call obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_Call(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public Call(Account acc, int call_id) {
        this(pjsua2JNI.new_Call__SWIG_0(Account.getCPtr(acc), acc, call_id), true);
        pjsua2JNI.Call_director_connect(this, swigCPtr, swigCMemOwn, true);
    }

    public CallInfo getInfo() throws java.lang.Exception {
        return new CallInfo(pjsua2JNI.Call_getInfo(swigCPtr, this), true);
    }

    public int getId() {
        return pjsua2JNI.Call_getId(swigCPtr, this);
    }

    public Media getMedia(long med_idx) {
        long cPtr = pjsua2JNI.Call_getMedia(swigCPtr, this, med_idx);
        return (cPtr == 0) ? null : new Media(cPtr, false);
    }

    public void makeCall(String dst_uri, CallOpParam prm) throws java.lang.Exception {
        pjsua2JNI.Call_makeCall(swigCPtr, this, dst_uri, CallOpParam.getCPtr(prm), prm);
    }

    public void answer(CallOpParam prm) throws java.lang.Exception {
        pjsua2JNI.Call_answer(swigCPtr, this, CallOpParam.getCPtr(prm), prm);
    }

    public void hangup(CallOpParam prm) throws java.lang.Exception {
        pjsua2JNI.Call_hangup(swigCPtr, this, CallOpParam.getCPtr(prm), prm);
    }

    public void onCallState(OnCallStateParam prm) {
    }

    public void onCallMediaState(OnCallMediaStateParam prm) {
    }
}
