/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class CallInfo {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected CallInfo(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CallInfo obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_CallInfo(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void setId(int value) {
        pjsua2JNI.CallInfo_id_set(swigCPtr, this, value);
    }

    public int getId() {
        return pjsua2JNI.CallInfo_id_get(swigCPtr, this);
    }

    public String getRemoteUri() {
        return pjsua2JNI.CallInfo_remoteUri_get(swigCPtr, this);
    }

    public pjsip_inv_state getState() {
        return pjsip_inv_state.swigToEnum(pjsua2JNI.CallInfo_state_get(swigCPtr, this));
    }

    public CallMediaInfoVector getMedia() {
        long cPtr = pjsua2JNI.CallInfo_media_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CallMediaInfoVector(cPtr, false);
    }
}
