/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class CallOpParam {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected CallOpParam(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CallOpParam obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_CallOpParam(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void setStatusCode(pjsip_status_code value) {
        pjsua2JNI.CallOpParam_statusCode_set(swigCPtr, this, value.swigValue());
    }

    public CallOpParam(boolean useDefaultCallSetting) {
        this(pjsua2JNI.new_CallOpParam__SWIG_0(useDefaultCallSetting), true);
    }

    public CallOpParam() {
        this(pjsua2JNI.new_CallOpParam__SWIG_1(), true);
    }

}
