/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class Endpoint {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Endpoint(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(Endpoint obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_Endpoint(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void libDestroy() throws java.lang.Exception {
        Runtime.getRuntime().gc();
        libDestroy_();
    }

    public Endpoint() {
        this(pjsua2JNI.new_Endpoint(), true);
        pjsua2JNI.Endpoint_director_connect(this, swigCPtr, swigCMemOwn, true);
    }

    public void libCreate() throws java.lang.Exception {
        pjsua2JNI.Endpoint_libCreate(swigCPtr, this);
    }

    public void libInit(EpConfig prmEpConfig) throws java.lang.Exception {
        pjsua2JNI.Endpoint_libInit(swigCPtr, this, EpConfig.getCPtr(prmEpConfig), prmEpConfig);
    }

    public void libStart() throws java.lang.Exception {
        pjsua2JNI.Endpoint_libStart(swigCPtr, this);
    }

    public void libRegisterThread(String name) throws java.lang.Exception {
        pjsua2JNI.Endpoint_libRegisterThread(swigCPtr, this, name);
    }

    public boolean libIsThreadRegistered() {
        return pjsua2JNI.Endpoint_libIsThreadRegistered(swigCPtr, this);
    }

    public void libDestroy_() throws java.lang.Exception {
        pjsua2JNI.Endpoint_libDestroy___SWIG_1(swigCPtr, this);
    }

    public int transportCreate(pjsip_transport_type_e type, TransportConfig cfg) throws java.lang.Exception {
        return pjsua2JNI.Endpoint_transportCreate(swigCPtr, this, type.swigValue(), TransportConfig.getCPtr(cfg), cfg);
    }

    public AudDevManager audDevManager() {
        return new AudDevManager(pjsua2JNI.Endpoint_audDevManager(swigCPtr, this), false);
    }
}
