/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class OnRegStateParam {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected OnRegStateParam(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(OnRegStateParam obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_OnRegStateParam(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public pjsip_status_code getCode() {
        return pjsip_status_code.swigToEnum(pjsua2JNI.OnRegStateParam_code_get(swigCPtr, this));
    }

    public String getReason() {
        return pjsua2JNI.OnRegStateParam_reason_get(swigCPtr, this);
    }

    public int getExpiration() {
        return pjsua2JNI.OnRegStateParam_expiration_get(swigCPtr, this);
    }

}
