/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class pjsua2JNI {
    public final static native String CallInfo_remoteUri_get(long jarg1, CallInfo jarg1_);

    public final static native boolean Endpoint_libIsThreadRegistered(long jarg1, Endpoint jarg1_);

    public final static native int Account_getId(long jarg1, Account jarg1_);

    public final static native int CallInfo_id_get(long jarg1, CallInfo jarg1_);

    public final static native int CallInfo_state_get(long jarg1, CallInfo jarg1_);

    public final static native int Call_getId(long jarg1, Call jarg1_);

    public final static native int Endpoint_transportCreate(long jarg1, Endpoint jarg1_, int jarg2, long jarg3, TransportConfig jarg3_) throws java.lang.Exception;

    public final static native int PJSIP_AC_AMBIGUOUS_get();

    public final static native int PJSIP_SC_ACCEPTED_get();

    public final static native int PJSIP_SC_ADDRESS_INCOMPLETE_get();

    public final static native int PJSIP_SC_ALTERNATIVE_SERVICE_get();

    public final static native int PJSIP_SC_BAD_EVENT_get();

    public final static native int PJSIP_SC_BAD_EXTENSION_get();

    public final static native int PJSIP_SC_BAD_GATEWAY_get();

    public final static native int PJSIP_SC_BAD_REQUEST_get();

    public final static native int PJSIP_SC_BUSY_EVERYWHERE_get();

    public final static native int PJSIP_SC_BUSY_HERE_get();

    public final static native int PJSIP_SC_CALL_BEING_FORWARDED_get();

    public final static native int PJSIP_SC_CALL_TSX_DOES_NOT_EXIST_get();

    public final static native int PJSIP_SC_DECLINE_get();

    public final static native int PJSIP_SC_DOES_NOT_EXIST_ANYWHERE_get();

    public final static native int PJSIP_SC_EXTENSION_REQUIRED_get();

    public final static native int PJSIP_SC_FORBIDDEN_get();

    public final static native int PJSIP_SC_GONE_get();

    public final static native int PJSIP_SC_INTERNAL_SERVER_ERROR_get();

    public final static native int PJSIP_SC_INTERVAL_TOO_BRIEF_get();

    public final static native int PJSIP_SC_LOOP_DETECTED_get();

    public final static native int PJSIP_SC_MESSAGE_TOO_LARGE_get();

    public final static native int PJSIP_SC_METHOD_NOT_ALLOWED_get();

    public final static native int PJSIP_SC_MOVED_PERMANENTLY_get();

    public final static native int PJSIP_SC_MOVED_TEMPORARILY_get();

    public final static native int PJSIP_SC_MULTIPLE_CHOICES_get();

    public final static native int PJSIP_SC_NOT_ACCEPTABLE_ANYWHERE_get();

    public final static native int PJSIP_SC_NOT_ACCEPTABLE_HERE_get();

    public final static native int PJSIP_SC_NOT_ACCEPTABLE_get();

    public final static native int PJSIP_SC_NOT_FOUND_get();

    public final static native int PJSIP_SC_NOT_IMPLEMENTED_get();

    public final static native int PJSIP_SC_OK_get();

    public final static native int PJSIP_SC_PAYMENT_REQUIRED_get();

    public final static native int PJSIP_SC_PRECONDITION_FAILURE_get();

    public final static native int PJSIP_SC_PROGRESS_get();

    public final static native int PJSIP_SC_PROXY_AUTHENTICATION_REQUIRED_get();

    public final static native int PJSIP_SC_QUEUED_get();

    public final static native int PJSIP_SC_REQUEST_ENTITY_TOO_LARGE_get();

    public final static native int PJSIP_SC_REQUEST_PENDING_get();

    public final static native int PJSIP_SC_REQUEST_TERMINATED_get();

    public final static native int PJSIP_SC_REQUEST_TIMEOUT_get();

    public final static native int PJSIP_SC_REQUEST_UPDATED_get();

    public final static native int PJSIP_SC_REQUEST_URI_TOO_LONG_get();

    public final static native int PJSIP_SC_RINGING_get();

    public final static native int PJSIP_SC_SERVER_TIMEOUT_get();

    public final static native int PJSIP_SC_SERVICE_UNAVAILABLE_get();

    public final static native int PJSIP_SC_SESSION_TIMER_TOO_SMALL_get();

    public final static native int PJSIP_SC_TEMPORARILY_UNAVAILABLE_get();

    public final static native int PJSIP_SC_TOO_MANY_HOPS_get();

    public final static native int PJSIP_SC_TRYING_get();

    public final static native int PJSIP_SC_TSX_TIMEOUT_get();

    public final static native int PJSIP_SC_TSX_TRANSPORT_ERROR_get();

    public final static native int PJSIP_SC_UNAUTHORIZED_get();

    public final static native int PJSIP_SC_UNDECIPHERABLE_get();

    public final static native int PJSIP_SC_UNSUPPORTED_MEDIA_TYPE_get();

    public final static native int PJSIP_SC_UNSUPPORTED_URI_SCHEME_get();

    public final static native int PJSIP_SC_USE_PROXY_get();

    public final static native int PJSIP_SC_VERSION_NOT_SUPPORTED_get();

    public final static native int PJSIP_SC__force_32bit_get();

    public final static native long AccountConfig_SWIGUpcast(long jarg1);

    public final static native long CallInfo_media_get(long jarg1, CallInfo jarg1_);

    public final static native long Call_getInfo(long jarg1, Call jarg1_) throws java.lang.Exception;

    public final static native long Call_getMedia(long jarg1, Call jarg1_, long jarg2);

    public final static native long Endpoint_audDevManager(long jarg1, Endpoint jarg1_);

    public final static native long EpConfig_SWIGUpcast(long jarg1);

    public final static native long TransportConfig_SWIGUpcast(long jarg1);

    public final static native long new_Account();

    public final static native long new_AccountCallConfig();

    public final static native long new_AccountConfig();

    public final static native long new_AccountInfo();

    public final static native long new_AccountMediaConfig();

    public final static native long new_AccountMwiConfig();

    public final static native long new_AccountNatConfig();

    public final static native long new_AccountPresConfig();

    public final static native long new_AccountRegConfig();

    public final static native long new_AccountSipConfig();

    public final static native long new_AccountVideoConfig();

    public final static native long new_Call__SWIG_0(long jarg1, Account jarg1_, int jarg2);

    public final static native long new_Endpoint();

    public final static native long new_EpConfig();

    public final static native long new_TransportConfig();

    public final static native void Account_create__SWIG_1(long jarg1, Account jarg1_, long jarg2, AccountConfig jarg2_) throws java.lang.Exception;

    public final static native void Account_director_connect(Account obj, long cptr, boolean mem_own, boolean weak_global);

    public final static native void Account_modify(long jarg1, Account jarg1_, long jarg2, AccountConfig jarg2_) throws java.lang.Exception;

    public final static native void CallInfo_id_set(long jarg1, CallInfo jarg1_, int jarg2);

    public final static native void Call_answer(long jarg1, Call jarg1_, long jarg2, CallOpParam jarg2_) throws java.lang.Exception;

    public final static native void Call_director_connect(Call obj, long cptr, boolean mem_own, boolean weak_global);

    public final static native void Call_hangup(long jarg1, Call jarg1_, long jarg2, CallOpParam jarg2_) throws java.lang.Exception;

    public final static native void Call_makeCall(long jarg1, Call jarg1_, String jarg2, long jarg3, CallOpParam jarg3_) throws java.lang.Exception;

    public final static native void Endpoint_director_connect(Endpoint obj, long cptr, boolean mem_own, boolean weak_global);

    public final static native void Endpoint_libCreate(long jarg1, Endpoint jarg1_) throws java.lang.Exception;

    public final static native void Endpoint_libDestroy___SWIG_1(long jarg1, Endpoint jarg1_) throws java.lang.Exception;

    public final static native void Endpoint_libInit(long jarg1, Endpoint jarg1_, long jarg2, EpConfig jarg2_) throws java.lang.Exception;

    public final static native void Endpoint_libRegisterThread(long jarg1, Endpoint jarg1_, String jarg2) throws java.lang.Exception;

    public final static native void Endpoint_libStart(long jarg1, Endpoint jarg1_) throws java.lang.Exception;

    public final static native void TransportConfig_port_set(long jarg1, TransportConfig jarg1_, long jarg2);

    public final static native void delete_Account(long jarg1);

    public final static native void delete_AccountCallConfig(long jarg1);

    public final static native void delete_AccountConfig(long jarg1);

    public final static native void delete_AccountInfo(long jarg1);

    public final static native void delete_AccountMediaConfig(long jarg1);

    public final static native void delete_AccountMwiConfig(long jarg1);

    public final static native void delete_AccountNatConfig(long jarg1);

    public final static native void delete_AccountPresConfig(long jarg1);

    public final static native void delete_AccountRegConfig(long jarg1);

    public final static native void delete_AccountSipConfig(long jarg1);

    public final static native void delete_AccountVideoConfig(long jarg1);

    public final static native void delete_Call(long jarg1);

    public final static native void delete_CallInfo(long jarg1);

    public final static native void delete_CallMediaInfo(long jarg1);

    public final static native void delete_CallMediaInfoVector(long jarg1);

    public final static native void delete_CallOpParam(long jarg1);

    public final static native void delete_CallSendRequestParam(long jarg1);

    public final static native void delete_CallSetting(long jarg1);

    public final static native void delete_CallVidSetStreamParam(long jarg1);

    public final static native void delete_Endpoint(long jarg1);

    public final static native void delete_EpConfig(long jarg1);

    public final static native void delete_PersistentObject(long jarg1);

    public final static native void delete_TransportConfig(long jarg1);

    public final static native String AccountConfig_idUri_get(long jarg1, AccountConfig jarg1_);

    public final static native String AuthCredInfo_data_get(long jarg1, AuthCredInfo jarg1_);

    public final static native String AuthCredInfo_username_get(long jarg1, AuthCredInfo jarg1_);

    public final static native String OnRegStateParam_reason_get(long jarg1, OnRegStateParam jarg1_);

    public final static native int CallMediaInfo_status_get(long jarg1, CallMediaInfo jarg1_);

    public final static native int CallMediaInfo_type_get(long jarg1, CallMediaInfo jarg1_);

    public final static native int OnIncomingCallParam_callId_get(long jarg1, OnIncomingCallParam jarg1_);

    public final static native int OnRegStateParam_code_get(long jarg1, OnRegStateParam jarg1_);

    public final static native int OnRegStateParam_expiration_get(long jarg1, OnRegStateParam jarg1_);

    public final static native int PJSIP_TRANSPORT_IPV6_get();

    public final static native int PJSIP_TRANSPORT_TCP6_get();

    public final static native int PJSIP_TRANSPORT_TLS6_get();

    public final static native int PJSIP_TRANSPORT_UDP6_get();

    public final static native long AccountConfig_natConfig_get(long jarg1, AccountConfig jarg1_);

    public final static native long AccountConfig_regConfig_get(long jarg1, AccountConfig jarg1_);

    public final static native long AccountConfig_sipConfig_get(long jarg1, AccountConfig jarg1_);

    public final static native long AccountNatConfig_SWIGUpcast(long jarg1);

    public final static native long AccountRegConfig_SWIGUpcast(long jarg1);

    public final static native long AccountSipConfig_SWIGUpcast(long jarg1);

    public final static native long AccountSipConfig_authCreds_get(long jarg1, AccountSipConfig jarg1_);

    public final static native long AccountSipConfig_proxies_get(long jarg1, AccountSipConfig jarg1_);

    public final static native long AudDevManager_getCaptureDevMedia(long jarg1, AudDevManager jarg1_) throws java.lang.Exception;

    public final static native long AudDevManager_getPlaybackDevMedia(long jarg1, AudDevManager jarg1_) throws java.lang.Exception;

    public final static native long AudioMedia_SWIGUpcast(long jarg1);

    public final static native long AudioMedia_typecastFromMedia(long jarg1, Media jarg1_);

    public final static native long AuthCredInfoVector_get(long jarg1, AuthCredInfoVector jarg1_, int jarg2);

    public final static native long AuthCredInfoVector_size(long jarg1, AuthCredInfoVector jarg1_);

    public final static native long AuthCredInfo_SWIGUpcast(long jarg1);

    public final static native long CallMediaInfoVector_get(long jarg1, CallMediaInfoVector jarg1_, int jarg2);

    public final static native long CallMediaInfoVector_size(long jarg1, CallMediaInfoVector jarg1_);

    public final static native long new_AuthCredInfo__SWIG_1(String jarg1, String jarg2, String jarg3, int jarg4, String jarg5);

    public final static native long new_CallOpParam__SWIG_0(boolean jarg1);

    public final static native long new_CallOpParam__SWIG_1();

    public final static native void AccountConfig_idUri_set(long jarg1, AccountConfig jarg1_, String jarg2);

    public final static native void AccountNatConfig_iceEnabled_set(long jarg1, AccountNatConfig jarg1_, boolean jarg2);

    public final static native void AccountRegConfig_registrarUri_set(long jarg1, AccountRegConfig jarg1_, String jarg2);

    public final static native void AudioMedia_startTransmit(long jarg1, AudioMedia jarg1_, long jarg2, AudioMedia jarg2_) throws java.lang.Exception;

    public final static native void AuthCredInfoVector_add(long jarg1, AuthCredInfoVector jarg1_, long jarg2, AuthCredInfo jarg2_);

    public final static native void AuthCredInfoVector_clear(long jarg1, AuthCredInfoVector jarg1_);

    public final static native void CallOpParam_statusCode_set(long jarg1, CallOpParam jarg1_, int jarg2);

    public final static native void StringVector_add(long jarg1, StringVector jarg1_, String jarg2);

    public final static native void StringVector_clear(long jarg1, StringVector jarg1_);

    public final static native void delete_AudioMedia(long jarg1);

    public final static native void delete_AudioMediaPlayer(long jarg1);

    public final static native void delete_AudioMediaPlayerInfo(long jarg1);

    public final static native void delete_AudioMediaRecorder(long jarg1);

    public final static native void delete_AuthCredInfo(long jarg1);

    public final static native void delete_AuthCredInfoVector(long jarg1);

    public final static native void delete_Media(long jarg1);

    public final static native void delete_MediaConfig(long jarg1);

    public final static native void delete_MediaCoordinate(long jarg1);

    public final static native void delete_MediaEvent(long jarg1);

    public final static native void delete_MediaEventData(long jarg1);

    public final static native void delete_MediaFmtChangedEvent(long jarg1);

    public final static native void delete_MediaFormat(long jarg1);

    public final static native void delete_MediaFormatAudio(long jarg1);

    public final static native void delete_MediaFormatVideo(long jarg1);

    public final static native void delete_MediaSize(long jarg1);

    public final static native void delete_MediaTransportInfo(long jarg1);

    public final static native void delete_OnCallMediaStateParam(long jarg1);

    public final static native void delete_OnCallStateParam(long jarg1);

    public final static native void delete_OnIncomingCallParam(long jarg1);

    public final static native void delete_OnRegStateParam(long jarg1);

    public final static native void delete_StringVector(long jarg1);

    public static void SwigDirector_Account_onIncomingCall(Account jself, long prm) {
        jself.onIncomingCall(new OnIncomingCallParam(prm, false));
    }

    public static void SwigDirector_Account_onRegState(Account jself, long prm) {
        jself.onRegState(new OnRegStateParam(prm, false));
    }

    public static void SwigDirector_Call_onCallState(Call jself, long prm) {
        jself.onCallState(new OnCallStateParam(prm, false));
    }

    public static void SwigDirector_Call_onCallMediaState(Call jself, long prm) {
        jself.onCallMediaState(new OnCallMediaStateParam(prm, false));
    }

    private final static native void swig_module_init();

    static {
        swig_module_init();
    }
}
