/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class StringVector {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected StringVector(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(StringVector obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_StringVector(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void clear() {
        pjsua2JNI.StringVector_clear(swigCPtr, this);
    }

    public void add(String x) {
        pjsua2JNI.StringVector_add(swigCPtr, this, x);
    }
}
